# Generated by Django 4.0.5 on 2022-06-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_schools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('author', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('date_of_Publication', models.DateField(max_length=122)),
                ('number_of_Pages', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('principal', models.CharField(max_length=122)),
                ('phone', models.IntegerField(max_length=12)),
                ('address2', models.TextField(max_length=122)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
