# Generated by Django 4.0.5 on 2022-06-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_books_schools_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('author', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('date_of_Publication', models.DateField(max_length=122)),
                ('number_of_Pages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('principal', models.CharField(max_length=122)),
                ('phone', models.IntegerField()),
                ('address2', models.TextField(max_length=122)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Schools',
        ),
    ]
