# Generated by Django 4.0.5 on 2022-06-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_book_school_delete_books_delete_schools'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
    ]
